#!/bin/sh
rm -rf obj_dir
rm -f top.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc rom.sv
verilator -Wall --cc counter.sv
verilator -Wall --cc --trace sinegen.sv --exe sinegen_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f  Vsinegen.mk Vsinegen

# run executable simulation file
obj_dir/Vsinegen